// generated by choreoc from "the-separation" — do not edit; edit the .choreo source
// run: node <repo>/choreo/verify/src/cli.mjs <this file>
import { fileURLToPath } from 'node:url';

export default {
  name: "the-separation",
  target: new URL("./the-separation.html", import.meta.url).href,
  mode: 'seek',
  viewport: { w: 800, h: 450 },
  duration: 8600,
  fps: 30,
  outDir: fileURLToPath(new URL('./.choreo', import.meta.url)),
  entities: {
    "moon": "#moon",
    "star1": "#star1",
    "star2": "#star2",
    "star3": "#star3",
    "ground": "#ground",
    "bench_back": "#bench_back",
    "leg1": "#leg1",
    "leg2": "#leg2",
    "bench_seat": "#bench_seat",
    "him": "#him",
    "her": "#her",
    "heart_l": "#heart_l",
    "heart_r": "#heart_r",
    "crack": "#crack",
    "drop1": "#drop1",
    "drop2": "#drop2",
    "drop3": "#drop3",
    "drop4": "#drop4",
    "title": "#title",
    "sub": "#sub"
  },
  checks: [
    {
      "at": 100,
      "assert": [
        "hidden(him)",
        "hidden(her)",
        "hidden(title)",
        "hidden(sub)",
        "hidden(drop1)",
        "hidden(drop4)"
      ]
    },
    {
      "during": [
        50,
        650
      ],
      "assert": [
        "fadesIn(moon)",
        "fadesIn(ground)",
        "fadesIn(bench_seat)"
      ]
    },
    {
      "during": [
        750,
        1200
      ],
      "assert": [
        "fadesIn(him)",
        "fadesIn(her)"
      ]
    },
    {
      "at": 1300,
      "assert": [
        "visible(heart_l)",
        "visible(heart_r)"
      ]
    },
    {
      "during": [
        1300,
        1500
      ],
      "assert": [
        "grows(heart_l)",
        "grows(heart_r)"
      ]
    },
    {
      "during": [
        2300,
        2700
      ],
      "assert": [
        "visible(crack)"
      ]
    },
    {
      "during": [
        2800,
        3300
      ],
      "assert": [
        "movesLeft(heart_l)",
        "movesRight(heart_r)"
      ]
    },
    {
      "at": 3400,
      "assert": [
        "notOverlapping(heart_l, heart_r)"
      ]
    },
    {
      "during": [
        3800,
        5100
      ],
      "assert": [
        "movesLeft(him)",
        "movesRight(her)"
      ]
    },
    {
      "during": [
        3800,
        4700
      ],
      "assert": [
        "fadesIn(drop1)",
        "movesDown(drop1)"
      ]
    },
    {
      "during": [
        4200,
        5080
      ],
      "assert": [
        "fadesIn(drop4)",
        "movesDown(drop4)"
      ]
    },
    {
      "at": 5300,
      "assert": [
        "leftOf(him, bench_seat)"
      ]
    },
    {
      "atEnd": true,
      "assert": [
        "leftOf(him, her)",
        "rightOf(her, bench_seat)",
        "above(title, bench_seat)"
      ]
    },
    {
      "always": true,
      "assert": [
        "onScreen(him)",
        "onScreen(her)",
        "onScreen(heart_l)",
        "onScreen(heart_r)"
      ]
    },
    {
      "during": [
        6200,
        6700
      ],
      "assert": [
        "fadesIn(sub)"
      ]
    },
    {
      "atEnd": true,
      "assert": [
        "fadedIn(him)",
        "fadedIn(her)",
        "fadedOut(heart_l)",
        "fadedOut(heart_r)",
        "fadedOut(crack)",
        "fadedIn(title)",
        "fadedIn(sub)",
        "settled(all)"
      ]
    },
    {
      "trace": true,
      "assert": [
        "appearsBefore(bench_seat, him)",
        "appearsBefore(her, drop1)",
        "appearsBefore(drop1, title)"
      ]
    }
  ],
};
