// Choreo codegen — compiled scene → self-contained HTML + @choreo-oss/verify spec.

function esc(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function round(n) { return Math.round(n * 100) / 100; }

function svgElement(e, perEntity) {
  const a = e.attrs;
  const common = [];
  if (a.opacity !== undefined) common.push(`opacity="${a.opacity}"`);
  const stroke = a.stroke ? `stroke="${esc(a.stroke)}"` : '';
  const sw = a.strokeWidth !== undefined ? `stroke-width="${a.strokeWidth}"` : '';
  const pathLen = perEntity[e.name]?.needsPathLength ? `pathLength="1"` : '';
  const x = round(e.cx - e.w / 2), y = round(e.cy - e.h / 2);

  switch (e.kind) {
    case 'rect':
      return `<rect id="${e.name}" x="${x}" y="${y}" width="${e.w}" height="${e.h}"` +
        ` rx="${a.radius ?? 0}" fill="${esc(a.fill ?? '#334155')}" ${stroke} ${sw} ${pathLen} ${common.join(' ')}/>`;
    case 'circle':
      return `<circle id="${e.name}" cx="${round(e.cx)}" cy="${round(e.cy)}" r="${e.r}"` +
        ` fill="${esc(a.fill ?? (a.stroke ? 'none' : '#334155'))}" ${stroke} ${sw} ${pathLen} ${common.join(' ')}/>`;
    case 'ellipse':
      return `<ellipse id="${e.name}" cx="${round(e.cx)}" cy="${round(e.cy)}" rx="${e.rx}" ry="${e.ry}"` +
        ` fill="${esc(a.fill ?? '#334155')}" ${stroke} ${sw} ${pathLen} ${common.join(' ')}/>`;
    case 'line':
      return `<line id="${e.name}" x1="${x}" y1="${round(e.cy)}" x2="${round(x + e.len)}" y2="${round(e.cy)}"` +
        ` stroke="${esc(a.stroke ?? '#94a3b8')}" stroke-width="${a.strokeWidth ?? 3}" stroke-linecap="round" ${pathLen} ${common.join(' ')}/>`;
    case 'arrow': {
      const color = a.stroke ?? '#94a3b8';
      // marker eats ~8px; shorten the shaft so the tip lands on the layout edge
      return `<line id="${e.name}" x1="${x}" y1="${round(e.cy)}" x2="${round(x + e.len - 8)}" y2="${round(e.cy)}"` +
        ` stroke="${esc(color)}" stroke-width="${a.strokeWidth ?? 3}" stroke-linecap="round"` +
        ` marker-end="url(#${e.name}-head)" ${pathLen} ${common.join(' ')}/>`;
    }
    case 'text':
      return `<text id="${e.name}" x="${round(e.cx)}" y="${round(e.cy)}" text-anchor="middle" dominant-baseline="central"` +
        ` font-size="${e.fontSize}" font-weight="${a.weight ?? 400}" fill="${esc(a.color ?? '#e2e8f0')}"` +
        ` ${a.font ? `font-family="${esc(a.font)}"` : ''} ${common.join(' ')}>${esc(e.text)}</text>`;
    case 'path':
      // wrapper <g> carries the id + animations; inner path carries the static position,
      // so CSS individual transforms and the positioning translate never conflict
      return `<g id="${e.name}"><path transform="translate(${x}, ${y})" d="${esc(e.d)}"` +
        ` fill="${esc(a.fill ?? 'none')}" ${stroke} ${sw} ${pathLen} ${common.join(' ')}/></g>`;
    default:
      throw new Error(`no codegen for entity kind "${e.kind}"`);
  }
}

function markers(entities) {
  const defs = entities
    .filter((e) => e.kind === 'arrow')
    .map((e) => `<marker id="${e.name}-head" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse">` +
      `<path d="M 0 0 L 10 5 L 0 10 z" fill="${esc(e.attrs.stroke ?? '#94a3b8')}"/></marker>`);
  return defs.length ? `  <defs>\n    ${defs.join('\n    ')}\n  </defs>\n` : '';
}

export function generateHtml(compiled) {
  const { ast, css } = compiled;
  const { scene, entities } = ast;
  const body = entities.map((e) => '  ' + svgElement(e, css.perEntity)).join('\n');
  return `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>${esc(scene.name)}</title>
<!-- generated by choreoc — do not edit; edit the .choreo source -->
<style>
html, body { margin: 0; }
body { display: grid; place-items: center; min-height: 100vh; background: ${esc(scene.background)}; font-family: system-ui, sans-serif; }
svg { display: block; }
${css.rules.join('\n')}
${css.keyframes.join('\n')}
</style>
</head>
<body>
<svg viewBox="0 0 ${scene.width} ${scene.height}" width="${scene.width}" height="${scene.height}">
${markers(entities)}${body}
</svg>
</body>
</html>
`;
}

export function generateSpec(compiled, htmlFilename) {
  const { ast, duration } = compiled;
  const entities = Object.fromEntries(ast.entities.map((e) => [e.name, `#${e.name}`]));
  const checks = ast.checks.map((c) => ({ ...c.scope, assert: c.asserts }));
  return `// generated by choreoc from "${ast.scene.name}" — do not edit; edit the .choreo source
// run: node <repo>/choreo/verify/src/cli.mjs <this file>
import { fileURLToPath } from 'node:url';

export default {
  name: ${JSON.stringify(ast.scene.name)},
  target: new URL(${JSON.stringify('./' + htmlFilename)}, import.meta.url).href,
  mode: 'seek',
  viewport: { w: ${ast.scene.width}, h: ${ast.scene.height} },
  duration: ${duration},
  fps: 30,
  outDir: fileURLToPath(new URL('./.choreo', import.meta.url)),
  entities: ${JSON.stringify(entities, null, 2).replace(/\n/g, '\n  ')},
  checks: ${JSON.stringify(checks, null, 2).replace(/\n/g, '\n  ')},
};
`;
}
